name: Build (Push/Pull request)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  _UNITY_VERSION: 2021.3.1f1

jobs:
  run-build:
    name: Build Libraries
    uses: ./.github/workflows/build.yml
    with:
      build-config: debug
      build-only-linux: false
      update-unity-native: false
  build-unity:
    name: Build Unity package
    if: "((github.event_name == 'push' && github.repository_owner == 'Cysharp') || startsWith(github.event.pull_request.head.label, 'Cysharp:'))"
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@
      - name: Build Unity (.unitypacakge)
        uses: Cysharp/Actions/.github/actions/unity-builder@main
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          projectPath: src/YetAnotherHttpHandler.Unity
          unityVersion: ${{ env._UNITY_VERSION }}
          targetPlatform: StandaloneLinux64
          buildMethod: PackageExporter.Export
      - uses: Cysharp/Actions/.github/actions/check-metas
        with:
          directory: src/YetAnotherHttpHandler.Unity