name: Build
on:
  workflow_dispatch:
    inputs:
      build-config:
        required: true
        default: 'debug'
        type: choice
        options:
          - debug
          - release
      build-only-linux:
        required: true
        default: false
        type: boolean

env:
  _RUST_BUILD_CONFIG: ${{ inputs.build-config == 'debug' && 'debug' || 'release' }}
  _DOTNET_BUILD_CONFIG: ${{ inputs.build-config == 'debug' && 'Debug' || 'Release' }}
  _UNITY_VERSION: 2021.3.1f

jobs:
  build-win-x64:
    name: Build Native library (win-x64)
    if: ${{ !inputs.build-only-linux }}
    runs-on: windows-2019
    timeout-minutes: 30
    defaults:
      run:
        working-directory: native
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - run: cargo build --target x86_64-pc-windows-msvc --profile ${{ env._RUST_BUILD_CONFIG == 'debug' && 'dev' || env._RUST_BUILD_CONFIG }}
      - uses: actions/upload-artifact@v3
        with:
          name: win-x64
          path: native/target/x86_64-pc-windows-msvc/${{ env._RUST_BUILD_CONFIG }}/yaha_native.dll
          retention-days: 1
      - run: dotnet test -c ${{ env._DOTNET_BUILD_CONFIG }} ../test/YetAnotherHttpHandler.Test

  build-linux-x64:
    name: Build Native library (linux-x64)
    runs-on: ubuntu-latest
    timeout-minutes: 30
    defaults:
      run:
        working-directory: native
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - run: cargo build --target x86_64-unknown-linux-gnu --profile ${{ env._RUST_BUILD_CONFIG == 'debug' && 'dev' || env._RUST_BUILD_CONFIG }}
      - uses: actions/upload-artifact@v3
        with:
          name: linux-x64
          path: native/target/x86_64-unknown-linux-gnu/${{ env._RUST_BUILD_CONFIG }}/libyaha_native.so
          retention-days: 1
      - run: dotnet test -c ${{ env._DOTNET_BUILD_CONFIG }} ../test/YetAnotherHttpHandler.Test

  build-osx-x64:
    name: Build Native library (osx-x64)
    if: ${{ !inputs.build-only-linux }}
    runs-on: macos-latest
    timeout-minutes: 30
    defaults:
      run:
        working-directory: native
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - run: cargo build --target x86_64-apple-darwin --profile ${{ env._RUST_BUILD_CONFIG == 'debug' && 'dev' || env._RUST_BUILD_CONFIG }}
      - uses: actions/upload-artifact@v3
        with:
          name: osx-x64
          path: native/target/x86_64-apple-darwin/${{ env._RUST_BUILD_CONFIG }}/libyaha_native.dylib
          retention-days: 1
      - run: dotnet test -c ${{ env._DOTNET_BUILD_CONFIG }} ../test/YetAnotherHttpHandler.Test

  build-osx-arm64:
    name: Build Native library (osx-arm64)
    if: ${{ !inputs.build-only-linux }}
    runs-on: macos-latest
    timeout-minutes: 30
    defaults:
      run:
        working-directory: native
    steps:
      - uses: actions/checkout@v3
      - run: rustup target add aarch64-apple-darwin
      - run: cargo build --target aarch64-apple-darwin --profile ${{ env._RUST_BUILD_CONFIG == 'debug' && 'dev' || env._RUST_BUILD_CONFIG }}
      - uses: actions/upload-artifact@v3
        with:
          name: osx-arm64
          path: native/target/aarch64-apple-darwin/${{ env._RUST_BUILD_CONFIG }}/libyaha_native.dylib
          retention-days: 1

  build-ios-x64:
    name: Build Native library (ios-x64)
    if: ${{ !inputs.build-only-linux }}
    runs-on: macos-latest
    timeout-minutes: 30
    defaults:
      run:
        working-directory: native
    steps:
      - uses: actions/checkout@v3
      - run: rustup target add x86_64-apple-ios
      - run: cargo build --target x86_64-apple-ios --profile ${{ env._RUST_BUILD_CONFIG == 'debug' && 'dev' || env._RUST_BUILD_CONFIG }}
      - uses: actions/upload-artifact@v3
        with:
          name: ios-x64
          path: native/target/x86_64-apple-ios/${{ env._RUST_BUILD_CONFIG }}/libyaha_native.a
          retention-days: 1

  build-ios-arm64:
    name: Build Native library (ios-arm64)
    if: ${{ !inputs.build-only-linux }}
    runs-on: macos-latest
    timeout-minutes: 30
    defaults:
      run:
        working-directory: native
    steps:
      - uses: actions/checkout@v3
      - run: rustup target add aarch64-apple-ios
      - run: cargo build --target aarch64-apple-ios --profile ${{ env._RUST_BUILD_CONFIG == 'debug' && 'dev' || env._RUST_BUILD_CONFIG }}
      - uses: actions/upload-artifact@v3
        with:
          name: ios-arm64
          path: native/target/aarch64-apple-ios/${{ env._RUST_BUILD_CONFIG }}/libyaha_native.a
          retention-days: 1

  build-android-arm64:
    name: Build Native library (android-arm64)
    if: ${{ !inputs.build-only-linux }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    defaults:
      run:
        working-directory: native
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt update && sudo apt install gcc-multilib
      - run: rustup target add aarch64-linux-android
      - run: cargo install cargo-ndk
      - run: cargo ndk -t arm64-v8a build --profile ${{ env._RUST_BUILD_CONFIG == 'debug' && 'dev' || env._RUST_BUILD_CONFIG }}
      - uses: actions/upload-artifact@v3
        with:
          name: anrdoid-arm64
          path: native/target/aarch64-linux-android/${{ env._RUST_BUILD_CONFIG }}/libyaha_native.so
          retention-days: 1

  build-dotnet:
    name: Build and pack .NET library
    if: ${{ inputs.build-only-linux && needs.build-linux-x64.result == 'success' || success() }}
    needs:
      - build-win-x64
      - build-linux-x64
      - build-osx-x64
      - build-osx-arm64
      - build-ios-x64
      - build-ios-arm64
      - build-android-arm64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          path: native/artifacts
      - run: ls -lFaR native/artifacts
      - run: dotnet pack -c ${{ env._DOTNET_BUILD_CONFIG }} ./YetAnotherHttpHandler.sln --include-symbols --include-source -o ./publish
      #- run: dotnet test -c ${{ env._DOTNET_BUILD_CONFIG }} ./test/YetAnotherHttpHandler.Packaging.Test
      - uses: actions/upload-artifact@v3
        with:
          name: nuget-packages
          path: ./publish/
          retention-days: 7

  build-unity:
    name: Pack native libraries for Unity
    if: ${{ inputs.build-only-linux && needs.build-dotnet.result == 'success' || success() }}
    needs: [ build-dotnet ]
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: nuget-packages
          path: ./publish/
      - run: unzip -o ./publish/YetAnotherHttpHandler.*[0-9].nupkg 'runtimes/*' -d src/YetAnotherHttpHandler.Unity/Assets/Plugins/Cysharp.Net.Http.YetAnotherHttpHandler.Native/
      - name: Export unitypackage
        uses: Cysharp/Actions/.github/actions/unity-builder@main
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          projectPath: src/YetAnotherHttpHandler.Unity
          unityVersion: ${{ env._UNITY_VERSION }}
          targetPlatform: StandaloneWindows
          buildMethod: PackageExporter.Export
      - run: echo "PACKAGE_VERSION=ci-$(date '+%Y%m%d-%H%M%S')+${GITHUB_SHA:0:6}" >> $GITHUB_ENV
      - name: Get Version
        run: echo "UNITY_PACKAGE_VERSION=$(cat src/YetAnotherHttpHandler.Unity/Assets/Plugins/Cysharp.Net.Http.YetAnotherHttpHandler.Native/package.json | jq -r '.version')" >> "$GITHUB_ENV"
      - uses: actions/upload-artifact@v1
        with:
          name: Cysharp.Net.Http.YetAnotherHttpHandler.Native.${{ env.PACKAGE_VERSION }}.unitypackage
          path: ./src/YetAnotherHttpHandler.Unity/Cysharp.Net.Http.YetAnotherHttpHandler.Native.${{ env.UNITY_PACKAGE_VERSION }}.unitypackage
